# Configuration of Hugo
title: Javier Martinez Hernandez
baseURL: "https://javiermtzhdez.github.io/"
enableRobotsTXT: true

############################
## LANGUAGE
############################
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################
build:
  writeStats: true
enableGitInfo: false
summaryLength: 30

pagination:
  pagerSize: 10

enableEmoji: true
footnotereturnlinkcontents: "<sup>^</sup>"
ignoreFiles: ['\.ipynb$', '.ipynb_checkpoints$', '\.Rmd$', '\.Rmarkdown$', '_cache$']
permalinks:
  authors: "/author/:slug/"
disableAliases: true

outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart

timeout: 600000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

# ——— keep one markup block ———
markup:
  highlight:
    lineNos: false
  goldmark:
    renderHooks:
      link:
        # modern replacement for enableDefault
        useEmbedded: fallback

security:
  _merge: deep

# ——— explicit sitemap so it’s clearly exposed ———
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
