name: Deploy website to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Hugo (extended)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.151.0'
          extended: true

      # Node for Tailwind & Pagefind
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Cache Hugo module cache (optional)
      - name: Cache Hugo module cache
        uses: actions/cache@v4
        with:
          path: /tmp/hugo_cache_runner/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      # Configure Pages (new API)
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      # Install Tailwind/PostCSS (or your existing deps)
      - name: Install JS dependencies
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            npm ci || npm install
          else
            npm init -y
            npm install -D tailwindcss postcss autoprefixer
          fi

      # Build site
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir || true)"
          hugo --minify --gc --baseURL "${{ steps.pages.outputs.base_url }}/"

      # Pagefind (only if you use it)
      - name: Generate Pagefind search index
        run: npx pagefind --site "public"

      # Upload static site artifact (new action version)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    if: github.repository_owner != 'HugoBlox'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
