name: Deploy website to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      # Hugo Modules often need Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.151.0'
          extended: true

      # (Optional but recommended) Vendor modules so builds are reproducible
      - name: Hugo mod vendor
        run: |
          hugo mod get -u
          hugo mod tidy
          hugo mod vendor

      # If you use Pagefind, you need Node to run npx
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir || true)"
          # Set the correct baseURL for GitHub Pages env
          hugo --minify --gc --baseURL "${{ steps.pages.outputs.base_url }}/"

      # Optional: Pagefind site search index (only if you actually use it)
      - name: Generate Pagefind search index
        run: npx pagefind --site "public"

      # Debug: ensure your verification file is in the output
      - name: List verification files
        run: |
          ls -l public/ | sed -n '1,200p' || true
          ls -l public | grep -E "google.*\.html|BingSiteAuth\.xml" || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    if: github.repository_owner != 'HugoBlox'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
